#create a new workflow for .Net core project 8.0 and push and pull request events to the main branch
#use linux as the runner

name: .NET Core

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
    build:
        name: "dotnet build"
        runs-on: ubuntu-latest
    
        steps:
        - uses: actions/checkout@v3
    
        - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
            dotnet-version: 3.1.301
    
        - name: Install dependencies
        run: dotnet restore
    
        - name: Build
        run: dotnet build --configuration Release --no-restore
